name: weather_app_gse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  auto_route: ^8.0.3
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  geolocator: ^12.0.0
  permission_handler: ^11.3.1

dev_dependencies:
  build_runner: ^2.4.8
  auto_route_generator: ^8.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_flavorizr:


flutter:
  uses-material-design: true
  assets:
    - .env