name: weather_app_gse
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  auto_route: ^8.0.3
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  freezed_annotation: ^2.4.1
  geolocator: ^12.0.0
  json_annotation: ^4.9.0
  permission_handler: ^11.3.1
  get_it: ^7.2.0
  injectable: ^2.4.4
  either_dart:

dev_dependencies:
  injectable_generator:
  
  freezed: ^2.4.7
  json_serializable:
  build_runner: ^2.4.8
  auto_route_generator: ^8.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_flavorizr:


flutter:
  uses-material-design: true
  assets:
    - .env